[package]
name = "nettoolskit-ui"
version.workspace = true
edition.workspace = true

[dependencies]
crossterm = { version = "0.28", features = ["event-stream"] }
owo-colors = "3.5"
thiserror = "1.0"
tracing = "0.1"
once_cell = "1.19"
nettoolskit-core = { path = "../core" }
nettoolskit-string-utils = { path = "../shared/string-utils" }

[lib]
name = "nettoolskit_ui"
path = "src/lib.rs"